### ISSUE TITLE
Chore: initialize project

### ISSUE THREAD

**Issue by Goonco** [swm-standard/phote_client#1]
### 🤔 Description

FE 프로젝트를 생성하고 관련된 패키지 설치 및 세팅을 진행한다.

<br>

### 📌 ToDo

- [ ] create-next-app 를 이용한 프로젝트 구성 및 불필요 파일 삭제
- [ ] issue template 생성
- [ ] vanilla-extract 설치 및 관련 세팅
- [ ] zustand 설치 및 관련 세팅
- [ ] MSW & Storybook 설치 및 관련 세팅
- [ ] tanstack-query 설치 및 관련 세팅

<br>

### 💬 Others

🤐🤐🤐 따로 없네여..

<br>
