### ISSUE TITLE
Refactor: refactor trivial codes according to mentoring

### ISSUE THREAD

**Issue by Goonco** [swm-standard/phote_client#19]
### 🤔 Description

* 23.07.16에 진행한 멘토링을 바탕으로 사소한 코드 리팩토링을 진행한다.

### 📌 ToDo

- [x] Controlled Input Component 구현 - #16
- [x] Story간 이동? Path parameter 관련 - #12
- [x] `endpoint.ts`, `routing.ts` 제거 - #12 
- [x] Storybook에서 request body 확인? - #16 
- [x] API 호출, mocking 반복적인 코드 - #18 
 
### 💬 Others

* 김현동 멘토님께 FE가 병목이라 지적받았음. 나 역시 리팩토링 및 좋은 코드를 고집하다 due date를 맞추지 못하는 것 만큼 멍청한 일도 없다고 생각함. 좀 더 빠르게 코드를 찍어내야겠음 😞

* 각 ToDo에 대한 자세한 사항은 PR에 기재
