### ISSUE TITLE
Chore: initialize project

### ISSUE THREAD

**Issue by Goonco** [swm-standard/phote_client#2]
### 🤔 Description

FE 프로젝트를 생성하고 관련된 패키지 설치 및 세팅을 진행한다.

### 📌 ToDo

- [X] create-next-app 를 이용한 프로젝트 구성 및 불필요 파일 삭제
- [X] issue template 생성
- [ ] PR template 생성
- [X] prettier 설정
- [X] vanilla-extract 설치 및 관련 세팅
- [X] zustand 설치 및 관련 세팅
- [X] Storybook 설치 및 관련 세팅
- [ ] MSW 설치 및 관련 세팅
- [ ] tanstack-query 설치 및 관련 세팅

### 💬 Others

MSW 및 tanstack-query는 후에 필요시 다시 설정하는 것로..
