### ISSUE TITLE
Feat: mock readWorkbooks API using MSW & Storybook

### ISSUE THREAD

**Issue by Goonco** [swm-standard/phote_client#5]
### 🤔 Description

* MSW와 Storybook을 이용해 `readWorkbooks` API를 모킹한다.

### 📌 ToDo

- [X] MSW 패키지 설치 및 설정
- [X] API 성공 상태 모킹
- [x] Tailwind로 간단한 스타일 적용

### 💬 Others

* 안되면 김현동 멘토님께 SOS칠 예정 🤤
* 근데 무사히 잘해버림 👊
